using System;
using System.Collections.Generic;
using Downstream.Core.Math;
using Downstream.Core.Race;
using Downstream.Core.Water;

namespace Downstream.Core.AI
{
    /// <summary>The design's line families: every track section ships a safe, a current-lane and an aggressive line, plus a shortcut where the river forks.</summary>
    public enum RacingLineKind : byte
    {
        Safe,
        CurrentLane,
        Aggressive,
        Shortcut,
    }

    /// <summary>A stretch of track where the shortcut line takes a different channel from the safe line.</summary>
    public struct ShortcutSection
    {
        public float Start;
        public float End;
    }

    /// <summary>
    /// One racing line: a lateral offset from the river centreline at every station along the track,
    /// plus the estimated time to run it. Offsets are in metres, positive to the right looking downstream.
    /// Generated by <see cref="RacingLineSet.Build"/>; designers can overwrite the offsets by hand
    /// (<see cref="SetLateral"/>) and call <see cref="RacingLineSet.Retime"/> afterwards.
    /// </summary>
    public sealed class RacingLine
    {
        private readonly float[] _lateral;
        private readonly float[] _flow;
        private readonly WaterFeature[] _features;
        private readonly float[] _timeTo;
        private readonly float _spacing;

        public RacingLineKind Kind { get; }
        public int StationCount => _lateral.Length;
        public IReadOnlyList<ShortcutSection> Shortcuts { get; internal set; } = Array.Empty<ShortcutSection>();

        internal RacingLine(RacingLineKind kind, float[] lateral, float spacing)
        {
            Kind = kind;
            _lateral = lateral;
            _spacing = spacing;
            _flow = new float[lateral.Length];
            _features = new WaterFeature[lateral.Length];
            _timeTo = new float[lateral.Length];
        }

        public float Lateral(int station) => _lateral[station];
        public void SetLateral(int station, float lateral) => _lateral[station] = lateral;

        /// <summary>Water speed along the track at a station on this line, m/s (negative in an eddy).</summary>
        public float FlowAt(int station) => _flow[station];
        public WaterFeature FeaturesAt(int station) => _features[station];

        /// <summary>Offset from the centreline at a distance along the track, linearly interpolated.</summary>
        public float LateralAt(float distance)
        {
            float f = distance / _spacing;
            if (f <= 0f) return _lateral[0];
            int i = (int)f;
            if (i >= _lateral.Length - 1) return _lateral[_lateral.Length - 1];
            return SimMath.Lerp(_lateral[i], _lateral[i + 1], f - i);
        }

        /// <summary>Estimated seconds to run this line from one track distance to another at the nominal boat speed.</summary>
        public float EstimatedTime(float from, float to) => TimeAt(to) - TimeAt(from);

        private float TimeAt(float distance)
        {
            float f = distance / _spacing;
            if (f <= 0f) return 0f;
            int i = (int)f;
            if (i >= _timeTo.Length - 1) return _timeTo[_timeTo.Length - 1];
            return SimMath.Lerp(_timeTo[i], _timeTo[i + 1], f - i);
        }

        internal void SetTiming(int station, float flow, WaterFeature features, float timeTo)
        {
            _flow[station] = flow;
            _features[station] = features;
            _timeTo[station] = timeTo;
        }

        /// <summary>True when <paramref name="distance"/> lies inside one of this line's shortcut sections.</summary>
        public bool InShortcut(float distance, out int section)
        {
            for (int s = 0; s < Shortcuts.Count; s++)
            {
                if (distance >= Shortcuts[s].Start && distance <= Shortcuts[s].End)
                {
                    section = s;
                    return true;
                }
            }
            section = -1;
            return false;
        }
    }

    public struct RacingLineSettings
    {
        /// <summary>Distance between stations along the track, metres.</summary>
        public float Spacing;
        /// <summary>How far either side of the centreline the cross-section scan looks, metres.</summary>
        public float ScanHalfWidth;
        public float ScanStep;
        /// <summary>Shallowest water a line may use, metres.</summary>
        public float MinDepth;
        /// <summary>Clearance a line keeps from banks and rocks, metres.</summary>
        public float Margin;
        /// <summary>Wider dry gaps than this separate the river from a parallel stretch of itself, not an island.</summary>
        public float MaxIslandWidth;
        /// <summary>Sideways metres a line may move per metre downstream.</summary>
        public float MaxLateralSlope;
        public int SmoothingPasses;
        /// <summary>Boat speed through still water used to time the lines, m/s.</summary>
        public float NominalSpeed;
        /// <summary>Race time the water is sampled at.</summary>
        public float SampleTime;

        public static RacingLineSettings Default => new RacingLineSettings
        {
            Spacing = 5f,
            ScanHalfWidth = 80f,
            ScanStep = 0.5f,
            MinDepth = 0.5f,
            Margin = 3f,
            MaxIslandWidth = 15f,
            MaxLateralSlope = 0.3f,
            SmoothingPasses = 40,
            NominalSpeed = 24f,
            SampleTime = 0f,
        };
    }

    /// <summary>
    /// The racing lines for one track, generated offline from the track centreline and the gameplay
    /// water (design: "an offline tool generates candidate lines from the track spline and flow field").
    /// Each station scans a cross-section of the river, finds the navigable channels and picks an offset
    /// per line family; the offsets are then smoothed and rate-limited so a boat can follow them.
    /// </summary>
    public sealed class RacingLineSet
    {
        private readonly SimVec3[] _right;
        private readonly float[] _curvature;
        private readonly RacingLine[] _lines;
        private readonly IWaterQuery _water;

        public RaceTrack Track { get; }
        public IWaterQuery Water => _water;
        public RacingLineSettings Settings { get; }
        public float Spacing => Settings.Spacing;
        public int StationCount => _right.Length;
        public IReadOnlyList<RacingLine> Lines => _lines;

        private RacingLineSet(RaceTrack track, IWaterQuery water, RacingLineSettings settings, SimVec3[] right, float[] curvature, RacingLine[] lines)
        {
            Track = track;
            _water = water;
            Settings = settings;
            _right = right;
            _curvature = curvature;
            _lines = lines;
        }

        /// <summary>The line of a family, or null when this track has none (no forks means no shortcut line).</summary>
        public RacingLine Get(RacingLineKind kind)
        {
            foreach (var l in _lines) if (l.Kind == kind) return l;
            return null;
        }

        /// <summary>Unit vector to the right of the river direction at a track distance.</summary>
        public SimVec3 RightAt(float distance)
        {
            float f = distance / Spacing;
            if (f <= 0f) return _right[0];
            int i = (int)f;
            if (i >= _right.Length - 1) return _right[_right.Length - 1];
            return SimVec3.Lerp(_right[i], _right[i + 1], f - i).Flat.Normalized;
        }

        /// <summary>Signed curvature of the centreline, radians per metre; positive bends to the right.</summary>
        public float CurvatureAt(float distance)
        {
            int i = SimMath.Min(SimMath.Max((int)(distance / Spacing + 0.5f), 0), _curvature.Length - 1);
            return _curvature[i];
        }

        public SimVec3 PointAt(float distance, float lateral) => Track.PointAt(distance) + RightAt(distance) * lateral;
        public SimVec3 PointOn(RacingLine line, float distance) => PointAt(distance, line.LateralAt(distance));

        /// <summary>Signed offset of a position from the centreline at a track distance.</summary>
        public float LateralOf(SimVec3 position, float distance) => SimVec3.Dot((position - Track.PointAt(distance)).Flat, RightAt(distance));

        public static RacingLineSet Build(RaceTrack track, IWaterQuery water) => Build(track, water, RacingLineSettings.Default);

        public static RacingLineSet Build(RaceTrack track, IWaterQuery water, RacingLineSettings settings)
        {
            int stations = (int)System.MathF.Ceiling(track.Length / settings.Spacing) + 1;
            var right = new SimVec3[stations];
            var heading = new float[stations];
            for (int i = 0; i < stations; i++)
            {
                float d = SimMath.Min(i * settings.Spacing, track.Length);
                var t = (track.PointAt(d + 2f) - track.PointAt(d - 2f)).Flat.Normalized;
                right[i] = new SimVec3(t.Z, 0f, -t.X);
                heading[i] = SimMath.Atan2(t.X, t.Z);
            }
            var curvature = new float[stations];
            for (int i = 0; i < stations; i++)
            {
                int a = SimMath.Max(0, i - 2), b = SimMath.Min(stations - 1, i + 2);
                curvature[i] = b > a ? SimMath.WrapAngle(heading[b] - heading[a]) / ((b - a) * settings.Spacing) : 0f;
            }

            var sections = new CrossSection[stations];
            for (int i = 0; i < stations; i++)
                sections[i] = CrossSection.Scan(track, water, settings, SimMath.Min(i * settings.Spacing, track.Length), right[i]);

            var lines = new List<RacingLine>();
            var safe = Choose(RacingLineKind.Safe, sections, curvature, settings, null);
            lines.Add(safe);
            lines.Add(Choose(RacingLineKind.CurrentLane, sections, curvature, settings, null));
            lines.Add(Choose(RacingLineKind.Aggressive, sections, curvature, settings, null));
            var shortcut = Choose(RacingLineKind.Shortcut, sections, curvature, settings, safe);
            if (shortcut.Shortcuts.Count > 0) lines.Add(shortcut);

            var set = new RacingLineSet(track, water, settings, right, curvature, lines.ToArray());
            set.Retime();
            return set;
        }

        /// <summary>Re-samples the water under every line and recomputes its timing (after hand edits).</summary>
        public void Retime()
        {
            foreach (var line in _lines)
            {
                float time = 0f;
                for (int i = 0; i < StationCount; i++)
                {
                    float d = SimMath.Min(i * Spacing, Track.Length);
                    var p = PointAt(d, line.Lateral(i));
                    var w = _water.Sample(p.X, p.Z, Settings.SampleTime);
                    var tangent = new SimVec3(-_right[i].Z, 0f, _right[i].X);
                    float flow = w.IsWet ? SimVec3.Dot(w.Flow, tangent) : 0f;
                    line.SetTiming(i, flow, w.IsWet ? w.Features : WaterFeature.None, time);
                    if (i == StationCount - 1) break;

                    // Inside of a bend is shorter: a right bend (positive curvature) shortens positive offsets.
                    float along = Spacing * SimMath.Max(0.2f, 1f - _curvature[i] * line.Lateral(i));
                    float across = line.Lateral(i + 1) - line.Lateral(i);
                    float length = SimMath.Sqrt(along * along + across * across);
                    float seconds = length / SimMath.Max(4f, Settings.NominalSpeed + flow);
                    if (!w.IsWet || w.Depth < Settings.MinDepth) seconds += 1f;
                    if ((w.Features & WaterFeature.HydraulicHole) != 0) seconds += 0.8f;
                    if ((w.Features & WaterFeature.Shallows) != 0) seconds += 0.1f;
                    time += seconds;
                }
            }
        }

        private static RacingLine Choose(RacingLineKind kind, CrossSection[] sections, float[] curvature, in RacingLineSettings settings, RacingLine safe)
        {
            int n = sections.Length;
            var lateral = new float[n];
            var lo = new float[n];
            var hi = new float[n];
            var split = new bool[n];
            float previous = 0f;
            for (int i = 0; i < n; i++)
            {
                var cs = sections[i];
                if (cs.Channels.Count == 0)
                {
                    lateral[i] = lo[i] = hi[i] = previous;
                    continue;
                }

                // Look a little ahead for the bend so the aggressive line sets up on the inside early.
                float bend = curvature[SimMath.Min(n - 1, i + 4)];
                int channel = cs.Nearest(previous);
                if (kind == RacingLineKind.Shortcut && safe != null && cs.Channels.Count >= 2)
                {
                    int safeChannel = cs.Nearest(safe.Lateral(i));
                    float best = float.MaxValue;
                    for (int c = 0; c < cs.Channels.Count; c++)
                    {
                        if (c == safeChannel) continue;
                        float cost = cs.BestCost(c, RacingLineKind.Aggressive, bend, settings, out _);
                        if (cost < best)
                        {
                            best = cost;
                            channel = c;
                        }
                    }
                    split[i] = true;
                }

                var scoringKind = kind == RacingLineKind.Shortcut ? RacingLineKind.Aggressive : kind;
                cs.BestCost(channel, scoringKind, bend, settings, out float chosen);
                cs.Bounds(channel, settings.Margin, chosen, out lo[i], out hi[i]);
                lateral[i] = chosen;
                previous = chosen;
            }

            Smooth(lateral, lo, hi, settings);
            var line = new RacingLine(kind, lateral, settings.Spacing);
            if (kind == RacingLineKind.Shortcut) line.Shortcuts = Sections(split, settings.Spacing);
            return line;
        }

        private static void Smooth(float[] lateral, float[] lo, float[] hi, in RacingLineSettings settings)
        {
            int n = lateral.Length;
            var tmp = new float[n];
            float step = settings.MaxLateralSlope * settings.Spacing;
            for (int pass = 0; pass < settings.SmoothingPasses; pass++)
            {
                tmp[0] = lateral[0];
                tmp[n - 1] = lateral[n - 1];
                for (int i = 1; i < n - 1; i++)
                    tmp[i] = SimMath.Clamp(0.25f * lateral[i - 1] + 0.5f * lateral[i] + 0.25f * lateral[i + 1], lo[i], hi[i]);
                Array.Copy(tmp, lateral, n);
            }
            // Rate-limit both ways so the line never asks for more sideways speed than a boat has, then
            // put it back inside the channel (a rock wins over the rate limit).
            for (int i = 1; i < n; i++) lateral[i] = SimMath.Clamp(SimMath.Clamp(lateral[i], lateral[i - 1] - step, lateral[i - 1] + step), lo[i], hi[i]);
            for (int i = n - 2; i >= 0; i--) lateral[i] = SimMath.Clamp(SimMath.Clamp(lateral[i], lateral[i + 1] - step, lateral[i + 1] + step), lo[i], hi[i]);
        }

        private static ShortcutSection[] Sections(bool[] split, float spacing)
        {
            var list = new List<ShortcutSection>();
            int start = -1;
            for (int i = 0; i <= split.Length; i++)
            {
                bool on = i < split.Length && split[i];
                if (on && start < 0) start = i;
                if (!on && start >= 0)
                {
                    // A one-station split is a rock the line brushes past, not a route choice.
                    if (i - start >= 2) list.Add(new ShortcutSection { Start = (start - 1) * spacing, End = i * spacing });
                    start = -1;
                }
            }
            return list.ToArray();
        }

        /// <summary>One scanned cross-section: per-sample navigability, clearance and water, grouped into channels.</summary>
        private sealed class CrossSection
        {
            public float[] Lateral;
            public bool[] Navigable;
            public float[] Clearance;
            public float[] Flow;
            public WaterFeature[] Features;
            public float[] HoleDistance;
            public readonly List<(int Start, int End)> Channels = new List<(int, int)>();

            public static CrossSection Scan(RaceTrack track, IWaterQuery water, in RacingLineSettings s, float distance, SimVec3 right)
            {
                int count = (int)(2f * s.ScanHalfWidth / s.ScanStep) + 1;
                var cs = new CrossSection
                {
                    Lateral = new float[count],
                    Navigable = new bool[count],
                    Clearance = new float[count],
                    Flow = new float[count],
                    Features = new WaterFeature[count],
                };
                var centre = track.PointAt(distance);
                var tangent = new SimVec3(-right.Z, 0f, right.X);
                for (int j = 0; j < count; j++)
                {
                    float lat = -s.ScanHalfWidth + j * s.ScanStep;
                    var p = centre + right * lat;
                    var w = water.Sample(p.X, p.Z, s.SampleTime);
                    cs.Lateral[j] = lat;
                    cs.Navigable[j] = w.IsWet && w.Depth >= s.MinDepth;
                    cs.Flow[j] = w.IsWet ? SimVec3.Dot(w.Flow, tangent) : 0f;
                    cs.Features[j] = w.IsWet ? w.Features : WaterFeature.None;
                    // Holes can be shorter than the station spacing: look half a station downstream too.
                    var q = p + tangent * (s.Spacing * 0.5f);
                    var wq = water.Sample(q.X, q.Z, s.SampleTime);
                    if (wq.IsWet) cs.Features[j] |= wq.Features & WaterFeature.HydraulicHole;
                }

                // Distance to the nearest hydraulic hole across the section.
                cs.HoleDistance = new float[count];
                float hd = float.MaxValue;
                for (int j = 0; j < count; j++)
                {
                    hd = (cs.Features[j] & WaterFeature.HydraulicHole) != 0 ? 0f : hd + s.ScanStep;
                    cs.HoleDistance[j] = hd;
                }
                hd = float.MaxValue;
                for (int j = count - 1; j >= 0; j--)
                {
                    hd = (cs.Features[j] & WaterFeature.HydraulicHole) != 0 ? 0f : hd + s.ScanStep;
                    cs.HoleDistance[j] = SimMath.Min(cs.HoleDistance[j], hd);
                }

                // Clearance: distance to the nearest dry or too-shallow sample (or the scan edge).
                float run = 0f;
                for (int j = 0; j < count; j++)
                {
                    run = cs.Navigable[j] ? run + s.ScanStep : 0f;
                    cs.Clearance[j] = run;
                }
                run = 0f;
                for (int j = count - 1; j >= 0; j--)
                {
                    run = cs.Navigable[j] ? run + s.ScanStep : 0f;
                    cs.Clearance[j] = SimMath.Min(cs.Clearance[j], run);
                }

                // Channels: runs of navigable water. Keep only the group joined to the centreline by gaps
                // narrow enough to be rocks or islands; anything further is another stretch of the river.
                var runs = new List<(int, int)>();
                int start = -1;
                for (int j = 0; j <= count; j++)
                {
                    bool nav = j < count && cs.Navigable[j];
                    if (nav && start < 0) start = j;
                    if (!nav && start >= 0)
                    {
                        runs.Add((start, j - 1));
                        start = -1;
                    }
                }
                if (runs.Count == 0) return cs;

                int centreRun = 0;
                float bestGap = float.MaxValue;
                for (int r = 0; r < runs.Count; r++)
                {
                    float a = cs.Lateral[runs[r].Item1], b = cs.Lateral[runs[r].Item2];
                    float gap = a > 0f ? a : (b < 0f ? -b : 0f);
                    if (gap < bestGap)
                    {
                        bestGap = gap;
                        centreRun = r;
                    }
                }
                int first = centreRun, last = centreRun;
                while (first > 0 && cs.Lateral[runs[first].Item1] - cs.Lateral[runs[first - 1].Item2] <= s.MaxIslandWidth) first--;
                while (last < runs.Count - 1 && cs.Lateral[runs[last + 1].Item1] - cs.Lateral[runs[last].Item2] <= s.MaxIslandWidth) last++;

                // A channel too narrow to keep the margin is still listed only if it is the only one.
                for (int r = first; r <= last; r++)
                {
                    float width = cs.Lateral[runs[r].Item2] - cs.Lateral[runs[r].Item1];
                    if (width >= 2f * s.Margin) cs.Channels.Add(runs[r]);
                }
                if (cs.Channels.Count == 0) cs.Channels.Add(runs[centreRun]);
                return cs;
            }

            public int Nearest(float lateral)
            {
                int best = 0;
                float bestGap = float.MaxValue;
                for (int c = 0; c < Channels.Count; c++)
                {
                    float a = Lateral[Channels[c].Start], b = Lateral[Channels[c].End];
                    float gap = lateral < a ? a - lateral : (lateral > b ? lateral - b : 0f);
                    if (gap < bestGap)
                    {
                        bestGap = gap;
                        best = c;
                    }
                }
                return best;
            }

            /// <summary>Lowest cost sample in a channel for a line family; samples closer than the margin to a bank only count when nothing else does.</summary>
            public float BestCost(int channel, RacingLineKind kind, float bend, in RacingLineSettings s, out float lateral)
            {
                var (start, end) = Channels[channel];
                float best = float.MaxValue;
                lateral = Lateral[(start + end) / 2];
                float maxClear = 0f;
                for (int j = start; j <= end; j++) maxClear = SimMath.Max(maxClear, Clearance[j]);
                float need = SimMath.Min(s.Margin, maxClear);
                for (int j = start; j <= end; j++)
                {
                    if (Clearance[j] < need) continue;
                    float cost = Cost(j, kind, bend);
                    if (cost < best)
                    {
                        best = cost;
                        lateral = Lateral[j];
                    }
                }
                return best;
            }

            private float Cost(int j, RacingLineKind kind, float bend)
            {
                var f = Features[j];
                float hazard = (HoleDistance[j] < 2f ? 1f : 0f)
                             + ((f & WaterFeature.Eddy) != 0 ? 1f : 0f)
                             + ((f & WaterFeature.Shallows) != 0 ? 0.5f : 0f);
                float clear = SimMath.Min(Clearance[j], 12f);
                switch (kind)
                {
                    case RacingLineKind.Safe:
                        return -clear + hazard * 20f;
                    case RacingLineKind.CurrentLane:
                        return -Flow[j] * 3f - ((f & WaterFeature.CurrentLane) != 0 ? 2f : 0f) + hazard * 10f - 0.2f * SimMath.Min(clear, 6f);
                    default:
                        // Aggressive: the inside of the coming bend, in fast water, crests welcome.
                        float inside = SimMath.Clamp(bend * 40f, -1f, 1f);
                        return -Lateral[j] * inside * 1.5f - Flow[j] + hazard * 6f - ((f & WaterFeature.Crest) != 0 ? 1f : 0f);
                }
            }

            /// <summary>
            /// The part of a channel a line may move in around its chosen point: samples with the margin of
            /// clearance from the banks and a little from any hole, so smoothing cannot drag a line that
            /// went round a hole back into it. Just the chosen point if nothing qualifies.
            /// </summary>
            public void Bounds(int channel, float margin, float chosen, out float lo, out float hi)
            {
                const float HoleMargin = 2f;
                var (start, end) = Channels[channel];
                int c = start;
                for (int j = start; j <= end; j++)
                    if (SimMath.Abs(Lateral[j] - chosen) < SimMath.Abs(Lateral[c] - chosen)) c = j;
                lo = hi = chosen;
                if (Clearance[c] < margin) return;
                bool avoidHoles = HoleDistance[c] >= HoleMargin;
                bool Ok(int j) => Clearance[j] >= margin && (!avoidHoles || HoleDistance[j] >= HoleMargin);
                int a = c, b = c;
                while (a > start && Ok(a - 1)) a--;
                while (b < end && Ok(b + 1)) b++;
                lo = SimMath.Min(Lateral[a], chosen);
                hi = SimMath.Max(Lateral[b], chosen);
            }
        }
    }
}
